# EKS Cluster Module Outputs

output "cluster_id" {
  description = "The name/id of the EKS cluster"
  value       = aws_eks_cluster.main.id
}

output "cluster_arn" {
  description = "The Amazon Resource Name (ARN) of the cluster"
  value       = aws_eks_cluster.main.arn
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = aws_eks_cluster.main.endpoint
}

output "cluster_version" {
  description = "The Kubernetes server version for the cluster"
  value       = aws_eks_cluster.main.version
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = aws_security_group.eks_cluster.id
}

output "node_security_group_id" {
  description = "Security group ID attached to the EKS nodes"
  value       = aws_security_group.eks_nodes.id
}

output "cluster_iam_role_arn" {
  description = "IAM role ARN of the EKS cluster"
  value       = aws_iam_role.eks_cluster.arn
}

output "node_iam_role_arn" {
  description = "IAM role ARN of the EKS node groups"
  value       = aws_iam_role.eks_node_group.arn
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = aws_eks_cluster.main.certificate_authority[0].data
  sensitive   = true
}

output "vpc_id" {
  description = "The ID of the VPC"
  value       = aws_vpc.eks_vpc.id
}

output "public_subnet_ids" {
  description = "List of IDs of public subnets"
  value       = aws_subnet.public[*].id
}

output "private_subnet_ids" {
  description = "List of IDs of private subnets"
  value       = aws_subnet.private[*].id
}

output "node_groups" {
  description = "Map of node groups and their details"
  value = {
    for k, v in aws_eks_node_group.main : k => {
      id            = v.id
      arn           = v.arn
      status        = v.status
      capacity_type = v.capacity_type
    }
  }
}

output "kubeconfig" {
  description = "kubectl config as generated by the module"
  value = {
    cluster_name                   = aws_eks_cluster.main.id
    endpoint                       = aws_eks_cluster.main.endpoint
    certificate_authority_data     = aws_eks_cluster.main.certificate_authority[0].data
    region                         = data.aws_region.current.name
  }
  sensitive = true
}

output "aws_auth_configmap" {
  description = "A kubernetes configuration to authenticate to this EKS cluster"
  value = templatefile("${path.module}/templates/aws-auth-cm.yaml.tpl", {
    node_role_arn = aws_iam_role.eks_node_group.arn
  })
}

output "cluster_oidc_issuer_url" {
  description = "The URL on the EKS cluster OIDC Issuer"
  value       = try(aws_eks_cluster.main.identity[0].oidc[0].issuer, null)
}
