# Root Module Outputs

output "cluster_id" {
  description = "The name/id of the EKS cluster"
  value       = module.eks_cluster.cluster_id
}

output "cluster_arn" {
  description = "The Amazon Resource Name (ARN) of the cluster"
  value       = module.eks_cluster.cluster_arn
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks_cluster.cluster_endpoint
}

output "cluster_version" {
  description = "The Kubernetes server version for the cluster"
  value       = module.eks_cluster.cluster_version
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.eks_cluster.cluster_security_group_id
}

output "node_security_group_id" {
  description = "Security group ID attached to the EKS nodes"
  value       = module.eks_cluster.node_security_group_id
}

output "vpc_id" {
  description = "The ID of the VPC"
  value       = module.eks_cluster.vpc_id
}

output "public_subnet_ids" {
  description = "List of IDs of public subnets"
  value       = module.eks_cluster.public_subnet_ids
}

output "private_subnet_ids" {
  description = "List of IDs of private subnets"
  value       = module.eks_cluster.private_subnet_ids
}

output "node_groups" {
  description = "Map of node groups and their details"
  value       = module.eks_cluster.node_groups
}

output "cluster_oidc_issuer_url" {
  description = "The URL on the EKS cluster OIDC Issuer"
  value       = module.eks_cluster.cluster_oidc_issuer_url
}

output "oidc_provider_arn" {
  description = "ARN of the OIDC Provider for IRSA"
  value       = var.enable_irsa ? aws_iam_openid_connect_provider.cluster[0].arn : null
}

output "kubeconfig_command" {
  description = "Command to update kubeconfig for cluster access"
  value       = "aws eks update-kubeconfig --region ${var.aws_region} --name ${module.eks_cluster.cluster_id}"
}

output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value       = module.eks_cluster.kubeconfig
  sensitive   = true
}

output "aws_auth_configmap" {
  description = "A kubernetes configuration to authenticate to this EKS cluster"
  value       = module.eks_cluster.aws_auth_configmap
}
